# Generated by Django 4.2.7 on 2026-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "can_read",
                    models.BooleanField(
                        default=False,
                        help_text="Can read own objects",
                        verbose_name="Can Read",
                    ),
                ),
                (
                    "can_read_all",
                    models.BooleanField(
                        default=False,
                        help_text="Can read all objects",
                        verbose_name="Can Read All",
                    ),
                ),
                (
                    "can_create",
                    models.BooleanField(
                        default=False,
                        help_text="Can create new objects",
                        verbose_name="Can Create",
                    ),
                ),
                (
                    "can_update",
                    models.BooleanField(
                        default=False,
                        help_text="Can update own objects",
                        verbose_name="Can Update",
                    ),
                ),
                (
                    "can_update_all",
                    models.BooleanField(
                        default=False,
                        help_text="Can update all objects",
                        verbose_name="Can Update All",
                    ),
                ),
                (
                    "can_delete",
                    models.BooleanField(
                        default=False,
                        help_text="Can delete own objects",
                        verbose_name="Can Delete",
                    ),
                ),
                (
                    "can_delete_all",
                    models.BooleanField(
                        default=False,
                        help_text="Can delete all objects",
                        verbose_name="Can Delete All",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Access Rule",
                "verbose_name_plural": "Access Rules",
                "db_table": "access_rules",
                "ordering": ["role__name", "element__name"],
            },
        ),
        migrations.CreateModel(
            name="BusinessElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the business element",
                        max_length=50,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Business Element",
                "verbose_name_plural": "Business Elements",
                "db_table": "business_elements",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Role Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted",
                        verbose_name="System Role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
