# Generated by Django 4.2.7 on 2026-01-14 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned By",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="permissions.role",
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="element",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_rules",
                to="permissions.businesselement",
                verbose_name="Business Element",
            ),
        ),
        migrations.AddField(
            model_name="accessrule",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_rules",
                to="permissions.role",
                verbose_name="Role",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="accessrule",
            unique_together={("role", "element")},
        ),
    ]
